linters:
  SelectorFormat:
    enabled: false

  ImportantRule:
    enabled: false

  ColorVariable:
    enabled: false

  LeadingZero:
    style: 'include_zero'

  QualifyingElement:
    enabled: false

  PlaceholderInExtend:
    enabled: false

  VendorPrefix:
    enabled: false
